version: '3.1'

services:
    mysql-container:
        image: mysql:latest
        ports:
          - 3306:3306
        environment:
          - MYSQL_ROOT_USER=root
          - MYSQL_ROOT_PASSWORD=pass
        volumes:
          - mysql-data:/var/lib/mysql

    phpmyadmin-container:
        image: phpmyadmin/phpmyadmin:latest
        ports:
          - 8080:80
        environment:
          - PMA_ARBITRARY=1
          - PMA_HOST=mysql-container
          - PMA_USER=root
          - PMA_PASSWORD=pass

    php-app-container:
        build:
          context: C:/Users/HP/Documents/VShtml/firstphp
        image: my-php-app
        ports:
          - 8081:80

volumes:
    mysql-data:
